
spring:
  redis:
    host: 127.0.0.1
    port: 6379


  datasource:
    username: root
    password: 3751ueoxjwgixjw3913
    url: jdbc:mysql://39.98.41.126:3306/monitor_server?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

constant:
  private_key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAMjeF/3kvdoyidcKAb3boa3qfB+3xGeEz7pQdWJ4Tg3nxXSzA28VVThdGuU2fija9Tx5nnPVzyzYAcSXrlyTmSIA+MLzacKBZ3iPWx2vZa/PXwH78NPg8tm6bhDPAgC+JB9p+nWpVsLp9iPQEvINeZ5o7mCLdfX1TSQiFQ9ZvMCpAgMBAAECgYBj5I9p5GfGK3wBRSi4kpFFPGeeHnW+RX5I2dqGre2jXLAF6UC77ZAEB8loVEFJcBqliJYUZTAyzPmUGxrLT1vHeyg1oce71oakgkk0S8HJYA8WjJchsd6kl28JOapNoYEo4mDnu1q8d8kNw3UxR7xmzYtSehD4O1Kn/Qgvi0zQAQJBAPRLMwvJGwhH90NKMi53HWMooz6/we9GC3iAqhsw+woawnDs7PUqa2G9yJ3sgiT80BJbnu9bYGhxAF4DjHxLFyECQQDSfi0r48iKEdhyCbRrRJ55FyaYo3KkojK/822r/zafr80MFB2ISxIjwy78VoiQiIFY0Zf4EiVaAG8MNFmdwWCJAkBHSi6iUNSvrPiuTVepkZ8k0bYZ2LHKlqFAUCPT/Y4026xEcg+QWAmwI0cJNvyfuJsr0EroRL00nU1jIhv8JZmhAkEAooL0ERyt6ZtZhsHjX6X8y/SJwfL/QghQMk6Y79/8plEueBLXsjBzctTw47VTfnNFmfNH5yjrWY9YLQ4F2nxAMQJBANX+/K1Cx8TBdxkffaVjoXDsBS0eQ0q3EL6CkATvKJNXiSazK5WBMPA/mx8tOs5kndmtghrceKqwKorY5mWAqWE=
  aes_key: Z6XB<$F9fA5jRT92

